apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: practicas
spec:
  selector:
    app: product-service
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8011
    targetPort: 8011
