apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: practicas
spec:
  selector:
    app: user-service
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8010
    targetPort: 8010
