# P7/cloudbuild.yaml
# Cloud Build para compilar, subir imágenes a Artifact Registry y desplegar a GKE

substitutions:
  _PROJECT_ID: "groovy-treat-472922-b3"   # Reemplaza con tu Project ID real
  _REGION: "us-central1"
  _CLUSTER: "practicas-sa-cluster"
  _NAMESPACE: "practicas-sa"
  _REPO: "microservices-repo"

steps:
  # 1. Configurar credenciales de gcloud
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Autenticando con GCP..."
        gcloud config set project $_PROJECT_ID
        gcloud container clusters get-credentials $_CLUSTER --zone $_REGION

  # 2. Build user-service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t", "us-central1-docker.pkg.dev/$_PROJECT_ID/$_REPO/user-service:latest",
        "./backend/user-service"
      ]

  # 3. Build product-service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t", "us-central1-docker.pkg.dev/$_PROJECT_ID/$_REPO/product-service:latest",
        "./backend/product-service"
      ]

  # 4. Push user-service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_REPO/user-service:latest"
      ]

  # 5. Push product-service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_REPO/product-service:latest"
      ]

  # 6. Desplegar a Kubernetes
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "apply",
        "-f",
        "./k8s/mysql-deployment.yaml",
        "-n",
        "$_NAMESPACE"
      ]

  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "apply",
        "-f",
        "./k8s/user-service-deployment.yaml",
        "-n",
        "$_NAMESPACE"
      ]

  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "apply",
        "-f",
        "./k8s/product-service-deployment.yaml",
        "-n",
        "$_NAMESPACE"
      ]

images:
  - "us-central1-docker.pkg.dev/$_PROJECT_ID/$_REPO/user-service:latest"
  - "us-central1-docker.pkg.dev/$_PROJECT_ID/$_REPO/product-service:latest"
