# P7/cloudbuild.yaml
# Cloud Build para compilar, subir y desplegar los microservicios en GKE

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _CLUSTER_NAME: "practicas-sa-cluster"
  _CLUSTER_ZONE: "us-central1-c"
  _NAMESPACE: "practicas-sa"

steps:
  # Paso 1: Autenticación en Artifact Registry
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth configure-docker us-central1-docker.pkg.dev

  # Paso 2: Build de user-service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'us-central1-docker.pkg.dev/groovy-treat-472922-b3/microservices-repo/user-service:latest',
        './backend/user-service'
      ]

  # Paso 3: Build de product-service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'us-central1-docker.pkg.dev/groovy-treat-472922-b3/microservices-repo/product-service:latest',
        './backend/product-service'
      ]

  # Paso 4: Push user-service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/groovy-treat-472922-b3/microservices-repo/user-service:latest'
      ]

  # Paso 5: Push product-service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/groovy-treat-472922-b3/microservices-repo/product-service:latest'
      ]

  # Paso 6: Aplicar despliegue en Kubernetes
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials $_CLUSTER_NAME --zone $_CLUSTER_ZONE --project groovy-treat-472922-b3
        kubectl apply -f k8s/mysql-deployment.yaml -n $_NAMESPACE
        kubectl apply -f k8s/user-service-deployment.yaml -n $_NAMESPACE
        kubectl apply -f k8s/product-service-deployment.yaml -n $_NAMESPACE

images:
  - 'us-central1-docker.pkg.dev/groovy-treat-472922-b3/microservices-repo/user-service:latest'
  - 'us-central1-docker.pkg.dev/groovy-treat-472922-b3/microservices-repo/product-service:latest'
