# cloudbuild.yaml para despliegue completo en GCP usando Kubernetes y Docker Hub

options:
  logging: CLOUD_LOGGING_ONLY  # evita problemas con service_account y logs

substitutions:
  _PROJECT_ID: "groovy-treat-472922-b3"
  _CLUSTER_NAME: "practicas-sa-cluster"
  _CLUSTER_ZONE: "us-central1-c"
  _NAMESPACE: "practicas-sa"

steps:
# 1️⃣ Configurar GKE
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Autenticando con GKE..."
      gcloud container clusters get-credentials $_CLUSTER_NAME --zone $_CLUSTER_ZONE --project $_PROJECT_ID

# 2️⃣ Crear namespace y secretos
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Aplicando namespace..."
      kubectl apply -f ./k8s/namespace.yaml
      echo "Aplicando secretos..."
      kubectl apply -f ./k8s/secrets.yaml

# 3️⃣ Desplegar MySQL
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Desplegando MySQL..."
      kubectl apply -f ./k8s/mysql-deployment.yaml -n $_NAMESPACE

# 4️⃣ Desplegar User Service
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Desplegando User Service..."
      kubectl apply -f ./k8s/user-service-deployment.yaml -n $_NAMESPACE

# 5️⃣ Desplegar Product Service
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Desplegando Product Service..."
      kubectl apply -f ./k8s/product-service-deployment.yaml -n $_NAMESPACE

# 6️⃣ Desplegar Frontend
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Desplegando Frontend..."
      kubectl apply -f ./k8s/frontend-deploy.yaml -n $_NAMESPACE

# 7️⃣ Desplegar Ingress
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Desplegando Ingress..."
      kubectl apply -f ./k8s/ingress.yaml -n $_NAMESPACE

# 8️⃣ Esperar a que todos los pods estén listos
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Esperando a que todos los pods estén listos..."
      kubectl wait --for=condition=Ready pods --all -n $_NAMESPACE --timeout=300s
