options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Paso 1: Configurar GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    id: 'Configurar GKE'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Obteniendo credenciales del cluster..."
        gcloud container clusters get-credentials practicas-sa-cluster \
          --zone us-central1-c \
          --project groovy-treat-472922-b3

  # Paso 2: Desplegar MySQL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    id: 'Desplegar MySQL'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Aplicando despliegue de MySQL..."
        kubectl apply -f k8s/mysql-deployment.yaml -n practicas-sa

  # Paso 3: Desplegar User Service (Docker Hub)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    id: 'Desplegar User Service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Aplicando despliegue de User Service..."
        sed -i 's|image:.*|image: esdrasjnl/user-service:latest|' k8s/user-service-deployment.yaml
        kubectl apply -f k8s/user-service-deployment.yaml -n practicas-sa

  # Paso 4: Desplegar Product Service (Docker Hub)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    id: 'Desplegar Product Service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Aplicando despliegue de Product Service..."
        sed -i 's|image:.*|image: esdrasjnl/product-service:latest|' k8s/product-service-deployment.yaml
        kubectl apply -f k8s/product-service-deployment.yaml -n practicas-sa

  # Paso 5: Esperar a que todos los pods estén listos
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    id: 'Esperar Pods Listos'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Esperando a que todos los pods estén listos..."
        kubectl wait --for=condition=Ready pods --all -n practicas-sa --timeout=300s

timeout: '1200s'
