prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi

alertmanager:
  enabled: true

grafana:
  enabled: true
  adminPassword: "GrafanaP@ssw0rd"
  persistence:
    enabled: false

kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
